# dataset info
dataset_name: "real_Date"
dataset_path: "/home/muahmmad/projects/Image_enhancement/Enhancement_Dataset"

# image info
chans: 3
im_width: 256
im_height: 256

# other params
val_interval: 1000 # steps
ckpt_interval: 10  # epochs
from_epoch : 0
num_epochs : 200
batch_size : 32
lr_rate : 0.001
num_critic : 10
gp_weight : 1
gp1_weight: 1
l1_weight : 100
lg_weight : 1
lambda_d : 10
lambda_d1 : 1
version : UIEB_syn_

#path_d : ./Par/model/Dne.pth
#path_t : ./Par/model/Tnet.pth
#path_a : ./Par/model/coe.pth

